version = 0.1
[default.deploy.parameters]
stack_name = "shareusefulness"
resolve_s3 = true
s3_prefix = "shareusefulness"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "LambdaArchitecture=\"x86_64\""
image_repositories = ["GetListFunction=147407883976.dkr.ecr.us-west-1.amazonaws.com/samapp1bd5fe610/getlistfunctionc957eda2repo", "AddLinkFunction=147407883976.dkr.ecr.us-west-1.amazonaws.com/samapp1bd5fe610/addlinkfunction7febb2a1repo"]
confirm_changeset = true
